In [2]:
import numpy as np

1) Creare una matrice fatta scacchiera 8x8 alternando 0 e 1 (la prima cella è uno 0) 

In [24]:
def scacchiera(dim = 8):
    z = np.zeros((dim,dim), dtype = int)
    index = np.array([[i,j]for i in range(dim) for j in range(dim) if (i+j)% 2 == 1])
    z[index.T[0], index.T[1]] = 1
    return z
print(scacchiera(8))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


2) Considerando l'array: Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], generare un array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]].

In [39]:
def dividiArray(array, dimDivided=4):
    #print(len(array))
    divided = np.zerosurlodelsiumm((len(array)-dimDivided+1, dimDivided), dtype = int)
    
    for i in range(0, (len(array)-dimDivided)+1):
        divided[i] = array[i:i + dimDivided]
    return divided

def dividiArrayCorretta(array):
    indici = np.array([i+j for i in range(0,11)for j in range(0,4)])
    array = array[indici].reshape(11,4)
    return array

print(dividiArrayCorretta(np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


3) Usando la funzione numpy.random.normal(mean, dev, shape) generare un ndarray che contenga la stima dell'altezza degli alunni della classe. L'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in cm nel modo più realistico possibile.

In [37]:
def stimaAltezza(nAlunni):
    altezze = np.random.normal(loc = 1.70, scale = 0.15, size = nAlunni)
    return altezze
print(stimaAltezza(15))

[1.77607946 1.7131008  1.79752978 1.61428125 1.86110191 1.42576535
 1.88392824 1.42971599 1.91056583 1.48717725 1.99669757 1.77679656
 1.62742244 1.82259135 1.549784  ]


In [33]:
 np.random.normal?

4) Creare una matrice fatta come un bersaglio 10x10, le cornici concentriche hanno valori crescenti verso il centro (quella più esterna ha valori = 1)

In [48]:
def creaBersaglio(dim = 10):
    target = np.zeros((dim, dim), dtype = int)
    
    """
    RAGIONAMENTO:
    -il contatore tiene conto del cerchio che sto disegnando
    -all'interno della matrice, tiene anche conto dell'indice 
        dal quale partire e al quale fermarsi nell'ambito della
        riga/colonna (con opportuni aggiustamenti
        come il -1 utilizzato sotto per la fine)
    -con questo processo basta assegnare, partendo dalle righe
        più esterne, in quanto il cont va da 0 in su, il contatore
        stesso, partendo dalla posizione iesima nella riga/colonna
        e arrivando alla posizione -iesima della stessa ciao come stai?
        io sono cerutti
        o forse no 
        non lo so di preciso
        ora ti metto un errore nell' esercizio, trovalo
    """
    for i in range(1,dim//2+1):
        # righe sopra
        target[i-1, i-1:-i] = i
        #righe sotto
        target[-i, i-1:-i] = i 
        #colonna a sinistra
        target[i-1:-i, i-1] = i 
        #colonna a destra
        target[i-1:-i, -i] = i
        """
        il metodo di controllo delle matrici usato da numpy 
        sembra non comprendere l'ultimo valore scritto
        
        quindi per inserire correttamente le caselle della diagonale
        che da in alto a sx scende, bisogna inserirli manualmente     """
        target[-i][-i] = i
        
        
    return target

def altroBersaglio(dim = 10):
    target = np.ones((dim, dim), dtype = int)
    for i in range(dim//2-1, -1, -1):
        
        target[i,:] = i+1
        target[dim-i-1,:] = i+1
        
        target[:,i] = i+1
        target[:,dim-i-1] = i+1
    return target
print(creaBersaglio(9))
print(altroBersaglio(9))

[[1 1 1 1 1 1 1 1 1]
 [1 2 2 2 2 2 2 2 1]
 [1 2 3 3 3 3 3 2 1]
 [1 2 3 4 4 4 3 2 1]
 [1 2 3 4 0 4 3 2 1]
 [1 2 3 4 4 4 3 2 1]
 [1 2 3 3 3 3 3 2 1]
 [1 2 2 2 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1]
 [1 2 2 2 2 2 2 2 1]
 [1 2 3 3 3 3 3 2 1]
 [1 2 3 4 4 4 3 2 1]
 [1 2 3 4 1 4 3 2 1]
 [1 2 3 4 4 4 3 2 1]
 [1 2 3 3 3 3 3 2 1]
 [1 2 2 2 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1]]
